(part "CY8C4014LQI-421"
    (packageRef "QFN50P300X300X60-17N-D")
    (interface
        (port "1" (symbPinId 1) (portName "P0.1") (portType INOUT))
        (port "2" (symbPinId 2) (portName "P0.2") (portType INOUT))
        (port "3" (symbPinId 3) (portName "P0.4") (portType INOUT))
        (port "4" (symbPinId 4) (portName "VCCD") (portType INOUT))
        (port "5" (symbPinId 5) (portName "VDDIO") (portType INOUT))
        (port "6" (symbPinId 6) (portName "VDD") (portType INOUT))
        (port "7" (symbPinId 7) (portName "VSS") (portType INOUT))
        (port "8" (symbPinId 8) (portName "P0.6") (portType INOUT))
        (port "9" (symbPinId 9) (portName "P1.1") (portType INOUT))
        (port "10" (symbPinId 10) (portName "P1.2") (portType INOUT))
        (port "11" (symbPinId 11) (portName "P1.3") (portType INOUT))
        (port "12" (symbPinId 12) (portName "P1.6") (portType INOUT))
        (port "13" (symbPinId 13) (portName "P1.7") (portType INOUT))
        (port "14" (symbPinId 14) (portName "P3.0") (portType INOUT))
        (port "15" (symbPinId 15) (portName "P3.1") (portType INOUT))
        (port "16" (symbPinId 16) (portName "P3.2") (portType INOUT))
        (port "17" (symbPinId 17) (portName "EP") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "101")
    (property "Manufacturer_Name" "Infineon")
    (property "Manufacturer_Part_Number" "CY8C4014LQI-421")
    (property "Mouser_Part_Number" "727-CY8C4014LQI-421")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/Cypress-Semiconductor/CY8C4014LQI-421?qs=h2odU9YHRxyINW4X3fOvRg%3D%3D")
    (property "Arrow_Part_Number" "")
    (property "Arrow_Price/Stock" "")
    (property "Description" "Cypress Semiconductor CY8C4014LQI-421, 32bit Microcontroller, CY8C4014, 16MHz, 16 kB Flash, 16-Pin QFN")
    (property "Datasheet_Link" "http://uk.rs-online.com/web/p/products/1783282")
    (property "symbolName1" "CY8C4014LQI-421")
)
