(part "CY8C4014LQI-422"
    (packageRef "QFN50P400X400X60-25N-D")
    (interface
        (port "1" (symbPinId 1) (portName "P0.0") (portType INOUT))
        (port "2" (symbPinId 2) (portName "P0.1") (portType INOUT))
        (port "3" (symbPinId 3) (portName "P0.2") (portType INOUT))
        (port "4" (symbPinId 4) (portName "P0.3") (portType INOUT))
        (port "5" (symbPinId 5) (portName "P0.4") (portType INOUT))
        (port "6" (symbPinId 6) (portName "VCCD") (portType INOUT))
        (port "7" (symbPinId 7) (portName "VDD") (portType INOUT))
        (port "8" (symbPinId 8) (portName "VSS") (portType INOUT))
        (port "9" (symbPinId 9) (portName "P0.5") (portType INOUT))
        (port "10" (symbPinId 10) (portName "P0.6") (portType INOUT))
        (port "11" (symbPinId 11) (portName "P0.7") (portType INOUT))
        (port "12" (symbPinId 12) (portName "P1.0") (portType INOUT))
        (port "13" (symbPinId 13) (portName "P1.1") (portType INOUT))
        (port "14" (symbPinId 14) (portName "P1.2") (portType INOUT))
        (port "15" (symbPinId 15) (portName "P1.3") (portType INOUT))
        (port "16" (symbPinId 16) (portName "P1.4") (portType INOUT))
        (port "17" (symbPinId 17) (portName "P1.5") (portType INOUT))
        (port "18" (symbPinId 18) (portName "P1.6") (portType INOUT))
        (port "19" (symbPinId 19) (portName "P1.7") (portType INOUT))
        (port "20" (symbPinId 20) (portName "P2.0") (portType INOUT))
        (port "21" (symbPinId 21) (portName "P3.0") (portType INOUT))
        (port "22" (symbPinId 22) (portName "P3.1") (portType INOUT))
        (port "23" (symbPinId 23) (portName "P3.2") (portType INOUT))
        (port "24" (symbPinId 24) (portName "XRES") (portType INOUT))
        (port "25" (symbPinId 25) (portName "EP") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "101")
    (property "Manufacturer_Name" "Infineon")
    (property "Manufacturer_Part_Number" "CY8C4014LQI-422")
    (property "Mouser_Part_Number" "727-CY8C4014LQI-422")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/Infineon-Technologies/CY8C4014LQI-422?qs=h2odU9YHRxwBFdYZzj5f5w%3D%3D")
    (property "Arrow_Part_Number" "CY8C4014LQI-422")
    (property "Arrow_Price/Stock" "https://www.arrow.com/en/products/cy8c4014lqi-422/cypress-semiconductor")
    (property "Description" "MCU 32-bit ARM Cortex M0 RISC 16KB Flash 2.5V/3.3V/5V 24-Pin QFN EP Tray")
    (property "Datasheet_Link" "https://www.cypress.com/file/138646/download")
    (property "symbolName1" "CY8C4014LQI-422")
)
